import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Archive,AudioLines,FileText,LockKeyhole,Plus,Search,Users} from 'lucide-react';
import {useCurrentUser} from '@/hooks/use-current-user';
import {usePageHeader} from '@/hooks/use-page-header';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {EntryDialog} from '@/components/bau/entry-dialog';
import {bauDb,errorMessage,loadBauOptions,type BauOptions,type BauSummary} from '@/lib/bau';
import {dayLabel} from '@/lib/agenda';
const blankOptions:BauOptions={projects:[],people:[],events:[]};
export function BauPage(){
 usePageHeader({title:'Baú'});const user=useCurrentUser(),navigate=useNavigate();
 const [options,setOptions]=useState<BauOptions>(blankOptions),[rows,setRows]=useState<BauSummary[]>([]),[query,setQuery]=useState(''),[project,setProject]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[scope,setScope]=useState('all'),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[create,setCreate]=useState(false),[refresh,setRefresh]=useState(0),[optionsError,setOptionsError]=useState('');
 useEffect(()=>{let active=true;loadBauOptions().then(data=>{if(active){setOptions(data);setOptionsError('');}}).catch(e=>{if(active)setOptionsError(errorMessage(e));});return()=>{active=false;};},[user.id,refresh]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{setLoading(true);setError('');if(from&&to&&from>to){setError('A data inicial deve ser anterior à final.');setLoading(false);return;}
  bauDb.rpc('talki_bau_search',{search_text:query.trim(),project_filter:project||null,from_day:from||null,to_day:to||null,scope,page_offset:page*30}).then(({data,error})=>{if(active){if(error)setError(errorMessage(error));else setRows(data??[]);setLoading(false);}});
 },250);return()=>{active=false;clearTimeout(timer);};},[query,project,from,to,scope,page,refresh,user.id]);
 return <div className="space-y-6 pb-6">
  <section className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2 flex items-center gap-2"><Archive className="size-3 text-primary"/>Memória do seu trabalho</p><h2 className="text-3xl font-semibold tracking-[-0.05em]">Baú</h2><p className="mt-2 text-sm text-muted-foreground">Guarde as conversas de hoje. Encontre as respostas de amanhã.</p></div><Button onClick={()=>setCreate(true)}><Plus/>Guardar reunião</Button></section>
  {optionsError&&<p role="alert" className="text-sm text-destructive">Não foi possível carregar projetos e pessoas. <button className="underline" onClick={()=>setRefresh(n=>n+1)}>Tentar novamente</button></p>}
  <div className="rounded-2xl border border-border bg-card/50 p-4"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input aria-label="Buscar no Baú" className="pl-9" placeholder="Buscar por título, participantes ou conteúdo da transcrição" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div><div className="mt-3 flex flex-wrap gap-3">
   <select aria-label="Filtrar meus registros e compartilhados" className="h-10 rounded-lg border border-input bg-background px-3 text-sm" value={scope} onChange={e=>{setScope(e.target.value);setPage(0);}}><option value="all">Todos os registros</option><option value="mine">Meu Baú</option><option value="shared">Compartilhados comigo</option></select>
   <select aria-label="Filtrar por projeto" className="h-10 max-w-full rounded-lg border border-input bg-background px-3 text-sm" value={project} onChange={e=>{setProject(e.target.value);setPage(0);}}><option value="">Todos os projetos</option>{options.projects.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select>
   <label className="flex items-center gap-2 text-xs text-muted-foreground">De<Input aria-label="Data inicial" className="w-auto" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/></label><label className="flex items-center gap-2 text-xs text-muted-foreground">Até<Input aria-label="Data final" className="w-auto" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></label>
  </div></div>
  {error?<div role="alert" className="rounded-xl border border-destructive/30 p-5"><p>{error}</p><Button variant="outline" className="mt-3" onClick={()=>setRefresh(n=>n+1)}>Tentar novamente</Button></div>:loading?<p className="py-12 text-center text-muted-foreground">Abrindo o Baú…</p>:rows.length===0?<div className="rounded-2xl border border-dashed border-border py-16 text-center"><Archive className="mx-auto mb-4 size-10 text-primary/60"/><h3 className="text-lg font-semibold">{query||project||from||to||scope!=='all'?'Nenhum registro encontrado':'Suas reuniões têm um lugar aqui'}</h3><p className="mx-auto mt-2 max-w-md px-4 text-sm text-muted-foreground">Guarde o áudio, anexe ou cole a transcrição e mantenha tudo organizado por reunião.</p><Button className="mt-5" onClick={()=>setCreate(true)}><Plus/>Guardar reunião</Button></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.slice(0,30).map(row=><Link key={row.id} to={`/bau/${row.id}`} className="group flex min-h-48 flex-col rounded-2xl border border-border bg-card/60 p-5 transition hover:border-primary/40 hover:bg-accent/30"><div className="mb-4 flex items-center justify-between gap-2"><span className="rounded-lg bg-primary/10 p-2 text-primary"><AudioLines className="size-5"/></span><span className="flex items-center gap-1.5 text-[11px] text-muted-foreground">{row.owner_id!==user.id?<><Users className="size-3"/>Compartilhado comigo</>:row.compartilhar_projeto?<><Users className="size-3"/>Compartilhado com projeto</>:<><LockKeyhole className="size-3"/>Meu registro</>}</span></div><h3 className="break-words text-base font-semibold group-hover:text-primary">{row.titulo}</h3><p className="mt-2 text-xs text-muted-foreground">{dayLabel(row.data_reuniao,{day:'numeric',month:'long',year:'numeric'})}{row.plan_id?` · ${options.projects.find(p=>p.id===row.plan_id)?.nome??'Projeto vinculado'}`:''}</p>{row.participantes&&<p className="mt-2 truncate text-xs text-muted-foreground">{row.participantes}</p>}<div className="mt-auto flex gap-4 pt-5 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><AudioLines className="size-3.5"/>{row.audios} áudio(s)</span><span className="flex items-center gap-1.5"><FileText className="size-3.5"/>{row.transcricoes} transcrição(ões)</span></div></Link>)}</div>}
  {(page>0||rows.length>30)&&<div className="flex justify-end gap-3"><Button variant="outline" disabled={loading||page===0} onClick={()=>setPage(n=>n-1)}>Anterior</Button><span className="self-center text-sm text-muted-foreground">Página {page+1}</span><Button variant="outline" disabled={loading||rows.length<=30} onClick={()=>setPage(n=>n+1)}>Próxima</Button></div>}
  {create&&<EntryDialog options={options} userId={user.id} onClose={()=>setCreate(false)} onSaved={id=>navigate(`/bau/${id}`)}/>}
 </div>;
}
