import {useCallback,useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {ArrowLeft,AudioLines,Download,FileText,LockKeyhole,Pencil,Share2,Trash2} from 'lucide-react';
import {toast} from 'sonner';
import {supabase} from '@/supabase';
import {useCurrentUser} from '@/hooks/use-current-user';
import {usePageHeader} from '@/hooks/use-page-header';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {EntryDialog} from '@/components/bau/entry-dialog';
import {SharingDialog} from '@/components/bau/sharing-dialog';
import {FileUploader} from '@/components/bau/file-uploader';
import {SecureAudio} from '@/components/bau/secure-audio';
import {BAU_BUCKET,MAX_TRANSCRIPT_CHARS,formatBytes} from '@/lib/bau-files';
import {bauDb,errorMessage,loadBauOptions,type BauEntry,type BauFile,type BauOptions} from '@/lib/bau';
import {dayLabel} from '@/lib/agenda';
export function BauDetailPage(){const {entryId=''}=useParams();return <BauDetailContent key={entryId} entryId={entryId}/>;}
function BauDetailContent({entryId}:{entryId:string}){
 const user=useCurrentUser(),navigate=useNavigate();
 const [entry,setEntry]=useState<BauEntry|null>(null),[files,setFiles]=useState<BauFile[]>([]),[options,setOptions]=useState<BauOptions>({projects:[],people:[],events:[]}),[error,setError]=useState(''),[optionsReady,setOptionsReady]=useState(false),[optionsError,setOptionsError]=useState('');
 const [editing,setEditing]=useState(false),[sharing,setSharing]=useState(false),[transcript,setTranscript]=useState(''),[editText,setEditText]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[deleting,setDeleting]=useState<BauFile|'entry'|null>(null);
 usePageHeader({title:entry?.titulo??'Baú',breadcrumb:[{label:'Baú',href:'/bau'}]});
 const load=useCallback(async()=>{try{const {data,error}=await bauDb.from('talki_bau_entries').select('id,owner_id,titulo,data_reuniao,participantes,notas,transcricao,plan_id,agenda_event_id,compartilhar_projeto,created_at,updated_at').eq('id',entryId).single();if(error)throw error;
  const rows:BauFile[]=[];for(let offset=0;;offset+=100){const result=await bauDb.from('talki_bau_files').select('id,entry_id,owner_id,nome,tipo,mime,tamanho,path,pronto,texto,created_at').eq('entry_id',entryId).order('created_at').order('id').range(offset,offset+99);if(result.error)throw result.error;rows.push(...result.data);if(result.data.length<100)break;}
  setEntry(data);setFiles(rows);setError('');
 }catch{setError('Este registro não está disponível ou você não tem mais acesso.');}},[entryId]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Load the persisted meeting when this route mounts.
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{let active=true;loadBauOptions().then(data=>{if(active){setOptions(data);setOptionsReady(true);}}).catch(()=>{if(active)setOptionsError('Não foi possível carregar os projetos e as pessoas. Atualize a página para editar ou compartilhar.');});return()=>{active=false;};},[user.id]);
 useEffect(()=>{const refresh=()=>void load();window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[load]);
 async function download(file:BauFile){try{const {data,error}=await supabase.storage.from(BAU_BUCKET).createSignedUrl(file.path,60,{download:file.nome});if(error)throw error;const a=document.createElement('a');a.href=data.signedUrl;a.download=file.nome;a.rel='noopener';a.click();}catch(e){toast.error(errorMessage(e));}}
 async function removeFile(file:BauFile){const result=await supabase.storage.from(BAU_BUCKET).remove([file.path]);if(result.error)throw result.error;const {error}=await bauDb.from('talki_bau_files').delete().eq('id',file.id).select('id').single();if(error)throw error;}
 async function remove(){if(!deleting||uploading)return;setBusy(true);try{if(deleting==='entry'){for(const file of files)await removeFile(file);const {error}=await bauDb.from('talki_bau_entries').delete().eq('id',entryId).eq('owner_id',user.id).select('id').single();if(error)throw error;toast.success('Registro excluído.');navigate('/bau');}else{await removeFile(deleting);toast.success('Arquivo excluído.');setDeleting(null);await load();}}catch(e){toast.error(errorMessage(e,'Não foi possível excluir tudo. Os arquivos restantes continuam no registro.'));await load();setDeleting(null);}finally{setBusy(false);}}
 async function saveText(){setBusy(true);try{const {error}=await bauDb.from('talki_bau_entries').update({transcricao:transcript.replaceAll('\u0000','')}).eq('id',entryId).eq('owner_id',user.id).select('id').single();if(error)throw error;setEditText(false);await load();toast.success('Transcrição salva e disponível na busca.');}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}
 if(error)return <div className="space-y-4 rounded-xl border border-border p-6"><p role="alert">{error}</p><Button variant="outline" onClick={()=>void load()}>Tentar novamente</Button><Link to="/bau" className="ml-3 text-sm text-primary">Voltar ao Baú</Link></div>;
 if(!entry)return <p className="py-12 text-center text-muted-foreground">Abrindo a reunião…</p>;
 const owner=entry.owner_id===user.id;
 return <div className="space-y-6 pb-6">
  <Link to="/bau" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Voltar ao Baú</Link>
  <section className="flex flex-col items-start justify-between gap-4 sm:flex-row"><div className="w-full min-w-0 sm:flex-1"><p className="eyebrow mb-2">{dayLabel(entry.data_reuniao,{day:'numeric',month:'long',year:'numeric'})}</p><h2 className="break-words text-3xl font-semibold tracking-[-0.05em]">{entry.titulo}</h2><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-3.5"/>{owner?'Seu registro · compartilhamento controlado por você':'Compartilhado com você · somente leitura'}</p></div>{owner&&<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!optionsReady||busy} onClick={()=>setEditing(true)}><Pencil/>Editar</Button><Button variant="outline" disabled={!optionsReady||busy} onClick={()=>setSharing(true)}><Share2/>Compartilhar</Button><Button variant="ghost" size="icon" aria-label="Excluir registro" disabled={busy||uploading} onClick={()=>setDeleting('entry')}><Trash2 className="text-destructive"/></Button></div>}</section>
  {optionsError&&<p role="alert" className="text-sm text-destructive">{optionsError}</p>}
  {(entry.participantes||entry.notas||entry.plan_id||entry.agenda_event_id)&&<div className="space-y-3 rounded-2xl border border-border bg-card/50 p-5">{entry.participantes&&<p className="text-sm"><span className="text-muted-foreground">Participantes: </span>{entry.participantes}</p>}{entry.plan_id&&<p className="text-sm text-muted-foreground">Projeto: {options.projects.find(p=>p.id===entry.plan_id)?<Link className="text-primary" to={`/tarefas/${entry.plan_id}`}>{options.projects.find(p=>p.id===entry.plan_id)?.nome}</Link>:'Projeto vinculado'}</p>}{entry.agenda_event_id&&<Link to="/agenda" className="block text-sm text-primary">Ver Agenda · {options.events.find(a=>a.id===entry.agenda_event_id)?.titulo??'Compromisso vinculado'}</Link>}{entry.notas&&<p className="whitespace-pre-wrap break-words text-sm leading-6">{entry.notas}</p>}</div>}
  <div className="grid gap-6 xl:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)]">
   <section className="space-y-4"><h3 className="flex items-center gap-2 text-lg font-semibold"><AudioLines className="size-5 text-primary"/>Arquivos da reunião</h3>
    {owner&&<FileUploader key={entry.id} entryId={entry.id} userId={user.id} pending={files.filter(f=>!f.pronto)} onChange={()=>void load()} onBusyChange={setUploading}/>}
    {files.map(file=><div key={file.id} className="space-y-3 rounded-xl border border-border bg-card/50 p-4"><div className="flex items-start gap-3">{file.tipo==='audio'?<AudioLines className="mt-1 size-5 shrink-0 text-primary"/>:<FileText className="mt-1 size-5 shrink-0 text-emerald-400"/>}<div className="min-w-0 flex-1"><p className="break-words text-sm font-medium">{file.nome}</p><p className="mt-1 text-xs text-muted-foreground">{formatBytes(file.tamanho)} · {file.pronto?'Guardado':'Envio pendente'}</p></div>{file.pronto&&<Button variant="ghost" size="icon-sm" aria-label={`Baixar ${file.nome}`} onClick={()=>void download(file)}><Download/></Button>}{owner&&<Button variant="ghost" size="icon-sm" aria-label={`Excluir ${file.nome}`} disabled={busy||uploading} onClick={()=>setDeleting(file)}><Trash2/></Button>}</div>{file.pronto&&file.tipo==='audio'&&<SecureAudio path={file.path}/>}</div>)}
    {!files.length&&!owner&&<p className="text-sm text-muted-foreground">Nenhum arquivo anexado.</p>}
   </section>
   <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="flex items-center gap-2 text-lg font-semibold"><FileText className="size-5 text-emerald-400"/>Transcrições</h3>{owner&&!editText&&<Button variant="outline" size="sm" onClick={()=>{setTranscript(entry.transcricao);setEditText(true);}}>{entry.transcricao?'Editar texto':'Colar transcrição'}</Button>}</div>
    {editText?<div className="space-y-3"><textarea aria-label="Texto da transcrição" className="min-h-96 w-full rounded-xl border border-input bg-background p-4 text-sm leading-7" maxLength={MAX_TRANSCRIPT_CHARS} value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Cole aqui a transcrição da reunião…"/><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{transcript.length.toLocaleString('pt-BR')} / 500.000 caracteres</span><div className="flex gap-2"><Button variant="outline" disabled={busy} onClick={()=>setEditText(false)}>Cancelar</Button><Button disabled={busy} onClick={()=>void saveText()}>{busy?'Salvando…':'Salvar transcrição'}</Button></div></div></div>:entry.transcricao?<div className="max-h-[640px] overflow-y-auto whitespace-pre-wrap break-words rounded-xl border border-border bg-card/50 p-5 text-sm leading-7">{entry.transcricao}</div>:<p className="rounded-xl border border-dashed border-border p-5 text-sm leading-6 text-muted-foreground">{owner?'Cole o texto ou envie um documento. A transcrição ficará disponível para leitura e busca no Baú.':'Nenhuma transcrição colada neste registro.'}</p>}
    {files.filter(f=>f.pronto&&f.tipo==='transcricao').map(file=><details key={file.id} className="rounded-xl border border-border bg-card/50 p-4" open><summary className="cursor-pointer break-words text-sm font-medium">{file.nome}</summary>{file.texto?<p className="mt-4 max-h-[480px] overflow-y-auto whitespace-pre-wrap break-words text-sm leading-7">{file.texto}</p>:<p className="mt-3 text-xs leading-5 text-muted-foreground">Arquivo preservado sem texto extraído. PDFs digitalizados precisam de uma transcrição colada para permitir a leitura e a busca.</p>}</details>)}
   </section>
  </div>
  {editing&&<EntryDialog entry={entry} options={options} userId={user.id} onClose={()=>setEditing(false)} onSaved={()=>void load()}/>}
  {sharing&&<SharingDialog entry={entry} options={options} onClose={()=>setSharing(false)} onSaved={()=>void load()}/>}
  {deleting&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><DialogContent><DialogHeader><DialogTitle>{deleting==='entry'?'Excluir reunião do Baú?':'Excluir arquivo?'}</DialogTitle><DialogDescription>{deleting==='entry'?'O registro, os áudios e as transcrições serão excluídos. Esta ação não pode ser desfeita.':`O arquivo “${deleting.nome}” será excluído permanentemente.`}</DialogDescription></DialogHeader><div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={()=>setDeleting(null)}>Cancelar</Button><Button variant="destructive" disabled={busy||uploading} onClick={()=>void remove()}>{busy?'Excluindo…':'Excluir'}</Button></div></DialogContent></Dialog>}
 </div>;
}
