/* eslint-disable react-hooks/set-state-in-effect -- Synchronize server data and route-driven forms after loading. */
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Play, Square, Pencil, Coffee, Sunset, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useCurrentUser } from '@/hooks/use-current-user';
import { usePageHeader } from '@/hooks/use-page-header';
import { useJornada } from '@/hooks/use-jornada';
import { readRows,rpc,type Registro } from '@/lib/jornada';
import { spDay,dayStart,addDays,secondsInRange,hours,clock } from '@/lib/jornada-metrics';
import { Field,Panel,Metric,JornadaNav,fieldClass } from '@/components/jornada/common';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
const empty={descricao:'',categoria_id:'',area_id:'',plan_id:'',task_id:'',participantes:'',inicio:'',fim:''};
function localInput(iso:string) {return new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(iso)).replace(' ','T');}
export function JornadaPage() {
 usePageHeader({title:'Minha jornada'});
 const user=useCurrentUser(),{data,error,reload}=useJornada();
 const [records,setRecords]=useState<Registro[]>([]),[day,setDay]=useState(spDay()),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[editing,setEditing]=useState<Registro|null>(null),[form,setForm]=useState(empty),[tasks,setTasks]=useState<{id:string;titulo:string;plan_id:string}[]>([]),[params,setParams]=useSearchParams();
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const loadRecords=useCallback(async()=>{try{setRecords(await readRows<Registro>('talki_registros',{user:user.id,order:'inicio'}));}catch(e){toast.error(e instanceof Error?e.message:'Erro ao carregar atividades');}},[user.id]);
 useEffect(()=>{if(!data)return;void loadRecords();const refresh=()=>void loadRecords();window.addEventListener('talki:jornada-change',refresh);window.addEventListener('focus',refresh);const interval=setInterval(refresh,15000);return()=>{window.removeEventListener('talki:jornada-change',refresh);window.removeEventListener('focus',refresh);clearInterval(interval);};},[data,loadRecords]);
 useEffect(()=>{if(!data)return;let mounted=true;readRows<{id:string;titulo:string;plan_id:string}>('tasks').then(rows=>{if(mounted)setTasks(rows);}).catch(e=>{if(mounted)toast.error(e instanceof Error?e.message:'Erro ao carregar tarefas');});return()=>{mounted=false;};},[data]);
 useEffect(()=>{const taskId=params.get('tarefa');if(!taskId||!data)return;const task=tasks.find(t=>t.id===taskId);if(!task)return;setForm({...empty,descricao:task.titulo,task_id:task.id,plan_id:task.plan_id,categoria_id:data.categorias.find(c=>/focado/i.test(c.nome))?.id??data.categorias[0]?.id??'',area_id:data.colaboradores.find(c=>c.user_id===user.id)?.area_id??'',inicio:localInput(new Date().toISOString())});setEditing(null);setOpen(true);setParams({}, {replace:true});},[params,data,tasks,setParams,user.id]);
 if(error)return <Panel><p role="alert">{error}</p><Button onClick={()=>void reload()}>Tentar novamente</Button></Panel>;
 if(!data)return <p className="text-muted-foreground">Carregando jornada…</p>;
 const me=data.colaboradores.find(c=>c.user_id===user.id);
 if(!me?.ativo)return <Panel>Seu acesso à Jornada está desativado. Procure a gestão.</Panel>;
 const active=records.filter(r=>!r.fim), start=dayStart(day),end=dayStart(addDays(day,1));
 const visible=records.filter(r=>secondsInRange(r,start,end,new Date().toISOString())>0 || spDay(r.inicio)===day);
 const total=records.reduce((sum,r)=>sum+secondsInRange(r,start,end),0);
 function begin(record?:Registro) {setEditing(record??null);setForm(record?{descricao:record.descricao,categoria_id:record.categoria_id,area_id:record.area_id??'',plan_id:record.plan_id??'',task_id:record.task_id??'',participantes:record.participantes??'',inicio:localInput(record.inicio),fim:record.fim?localInput(record.fim):''}:{...empty,categoria_id:data!.categorias[0]?.id??'',area_id:me?.area_id??'',inicio:localInput(new Date().toISOString())});setOpen(true);}
 async function action(name:string,payload:Record<string,unknown>={}) {setBusy(true);try{await rpc('talki_jornada_save',{p_action:name,p_data:payload});await loadRecords();return true;}catch(e){toast.error(e instanceof Error?e.message:'Falha ao registrar');return false;}finally{setBusy(false);}}
 async function save(e:FormEvent) {e.preventDefault();const ok=await action(editing?'edit':'start',{...form,id:editing?.id,inicio:new Date(form.inicio+'-03:00').toISOString(),fim:form.fim?new Date(form.fim+'-03:00').toISOString():null});if(ok){setOpen(false);toast.success(editing?'Atividade atualizada.':'Atividade iniciada.');}}
 return <><JornadaNav gestor={data.gestor}/><div className="grid gap-4 sm:grid-cols-3"><Metric label="Horas somadas das atividades encerradas" value={hours(total)}/><Metric label="Jornada contratada" value={`${me.horas_dia_contratadas} h/dia`}/><Metric label="Atividades no dia" value={visible.length}/></div>
 <Panel className="mt-5">
  <div className="flex flex-wrap items-center justify-between gap-4">
   <div><p className="text-sm text-muted-foreground">Agora</p><h2 className="mt-1 text-xl font-semibold">{active.length ? `${active.length} ${active.length===1?'atividade em andamento':'atividades em andamento'}` : 'Tudo pronto para começar'}</h2><p className="mt-1 text-sm text-muted-foreground">Você pode iniciar várias atividades ao mesmo tempo. Cada uma registra seu próprio tempo.</p></div>
   <div className="flex flex-wrap gap-2">
    <Button disabled={busy} onClick={()=>begin()}><Play/>Iniciar atividade</Button>
    <Button disabled={busy} variant="outline" onClick={()=>{const category=data.categorias.find(c=>/pausa/i.test(c.nome));if(category)void action('pause',{descricao:'Pausa',categoria_id:category.id,area_id:me.area_id});else toast.error('Cadastre uma categoria de pausa.');}}><Coffee/>{active.length?'Pausar todas':'Pausa'}</Button>
    <Button disabled={busy} variant="outline" onClick={()=>void action('end')}><Sunset/>Fim do expediente</Button>
   </div>
  </div>
  {active.length>0&&<div className="mt-5 divide-y divide-border">{active.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 py-3">
   <span className="size-2.5 shrink-0 rounded-full" style={{background:data.categorias.find(c=>c.id===r.categoria_id)?.cor}}/>
   <div className="min-w-0 flex-1"><p className="break-words font-medium">{r.descricao}</p><p className="text-xs text-muted-foreground">{data.categorias.find(c=>c.id===r.categoria_id)?.nome}{r.projeto_nome?` · ${r.projeto_nome}`:''}</p></div>
   <span className="font-mono text-sm tabular-nums">{clock((now-Date.parse(r.inicio))/1000)}</span>
   <Button disabled={busy} variant="secondary" size="sm" aria-label={`Encerrar ${r.descricao}`} onClick={()=>void action('finish',{id:r.id})}><Square/>Encerrar</Button>
  </div>)}</div>}
 </Panel>
 <Panel className="mt-5"><div className="mb-4 flex items-end justify-between gap-3"><Field label="Dia · horário de São Paulo"><input className={fieldClass} type="date" value={day} onChange={e=>setDay(e.target.value)} max={spDay()}/></Field><Button variant="ghost" onClick={()=>void loadRecords()}><RefreshCw/>Atualizar</Button></div><div className="divide-y divide-border">{visible.length===0?<p className="py-8 text-center text-muted-foreground">Nenhuma atividade neste dia.</p>:visible.map(r=><div key={r.id} className="flex items-center gap-4 py-4"><span className="size-2.5 shrink-0 rounded-full" style={{background:data.categorias.find(c=>c.id===r.categoria_id)?.cor}}/><div className="min-w-0 flex-1"><p className="font-medium">{r.descricao}</p><p className="text-xs text-muted-foreground">{data.categorias.find(c=>c.id===r.categoria_id)?.nome} · {localInput(r.inicio).replace('T',' ')}{r.fim?` → ${localInput(r.fim).replace('T',' ')}`:' · Em andamento'}{r.projeto_nome?` · ${r.projeto_nome}`:''}{r.tarefa_titulo?` / ${r.tarefa_titulo}`:''}</p></div><span className="text-sm tabular-nums">{r.fim?hours(secondsInRange(r,start,end)):'Ao vivo'}</span><Button variant="ghost" size="icon" aria-label={`Editar ${r.descricao}`} onClick={()=>begin(r)}><Pencil/></Button></div>)}</div></Panel>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editing?'Editar atividade':'Iniciar atividade'}</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-4"><Field label="O que você está fazendo?"><input className={fieldClass} required maxLength={4000} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Categoria"><select className={fieldClass} required value={form.categoria_id} onChange={e=>setForm({...form,categoria_id:e.target.value})}><option value="">Selecione</option>{data.categorias.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></Field><Field label="Área da atividade"><select className={fieldClass} value={form.area_id} onChange={e=>setForm({...form,area_id:e.target.value})}><option value="">Sem área</option>{data.areas.filter(a=>a.ativo||a.id===form.area_id).map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></Field><Field label="Projeto (opcional)"><select className={fieldClass} value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value,task_id:''})}><option value="">Sem projeto</option>{data.projetos.filter(p=>!data.settings.some(s=>s.plan_id===p.id&&!s.ativo)||p.id===form.plan_id).map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></Field><Field label="Tarefa (opcional)"><select className={fieldClass} value={form.task_id} onChange={e=>{const t=tasks.find(t=>t.id===e.target.value);setForm({...form,task_id:e.target.value,plan_id:t?.plan_id??form.plan_id});}}><option value="">Sem tarefa</option>{tasks.filter(t=>!form.plan_id||t.plan_id===form.plan_id).map(t=><option key={t.id} value={t.id}>{t.titulo}</option>)}</select></Field><Field label="Início · São Paulo"><input className={fieldClass} type="datetime-local" step="1" required value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})}/></Field><Field label="Fim (vazio = em andamento)"><input className={fieldClass} type="datetime-local" step="1" value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})}/></Field></div><Field label="Participantes (opcional)"><input className={fieldClass} value={form.participantes} onChange={e=>setForm({...form,participantes:e.target.value})}/></Field><Button disabled={busy} type="submit">{busy?'Salvando…':'Salvar atividade'}</Button></form></DialogContent></Dialog></>;
}
