/* eslint-disable react-hooks/set-state-in-effect -- Synchronize server data and route-driven forms after loading. */
import { useEffect,useState,type FormEvent } from 'react';
import { toast } from 'sonner';
import { useCurrentUser } from '@/hooks/use-current-user';
import { usePageHeader } from '@/hooks/use-page-header';
import { useJornada } from '@/hooks/use-jornada';
import { rpc,readRows,type Pontuacao } from '@/lib/jornada';
import { level } from '@/lib/jornada-metrics';
import { estagioDragao,temAsas } from '@/lib/jornada-dragao';
import DragaoSVG from '@/components/jornada/dragao-svg';
import { Field,Panel,JornadaNav,fieldClass } from '@/components/jornada/common';
import { Button } from '@/components/ui/button';
export function JornadaPerfilPage() {
 usePageHeader({title:'Perfil e engajamento'});const user=useCurrentUser(),{data,error,reload}=useJornada();
 const [points,setPoints]=useState<Pontuacao[]>([]),[busy,setBusy]=useState(false),[form,setForm]=useState({nome:'',sobrenome:'',cargo:'',descricao_cargo:'',data_nascimento:''});
 useEffect(()=>{if(!data)return;const p=data.pessoas.find(p=>p.id===user.id),c=data.colaboradores.find(c=>c.user_id===user.id);setForm({nome:p?.nome??'',sobrenome:c?.sobrenome??'',cargo:p?.cargo??'',descricao_cargo:c?.descricao_cargo??'',data_nascimento:c?.data_nascimento??''});void readRows<Pontuacao>('talki_pontuacao_diaria',{user:user.id,order:'data'}).then(setPoints).catch(e=>toast.error(e.message));},[data,user.id]);
 if(error)return <Panel>{error}</Panel>;if(!data)return <p>Carregando perfil…</p>;
 const me=data.colaboradores.find(c=>c.user_id===user.id);if(!me)return <Panel>Perfil indisponível.</Panel>;
 const recent=[...points].sort((a,b)=>b.data.localeCompare(a.data)),stage=estagioDragao(me.moedas);
 async function save(e:FormEvent) {e.preventDefault();setBusy(true);try{await rpc('talki_jornada_profile',{p_data:form});await reload();toast.success('Perfil atualizado.');}catch(e){toast.error(e instanceof Error?e.message:'Falha ao salvar');}finally{setBusy(false);}}
 return <><JornadaNav gestor={data.gestor}/><div className="grid gap-5 lg:grid-cols-[1fr_2fr]"><Panel><div className="flex flex-col items-center text-center"><DragaoSVG estagio={stage.chave} asas={temAsas(recent)} size={180}/><h2 className="text-2xl font-semibold">{stage.nome}</h2><p className="mt-2 text-muted-foreground">{me.moedas} moedas · {level(me.moedas)}</p><p className="mt-3 text-sm text-muted-foreground">{stage.descricao}</p><Button className="mt-4" disabled={busy||!me.ativo} onClick={async()=>{setBusy(true);try{await rpc('talki_jornada_score');await reload();toast.success('Pontuação atualizada.');}catch(e){toast.error(e instanceof Error?e.message:'Erro ao avaliar');}finally{setBusy(false);}}}>Atualizar dias encerrados</Button></div><div className="mt-5 border-t border-border pt-4 text-sm text-muted-foreground"><p>A pontuação é calculada no banco para dias anteriores com registros encerrados. Meta: 70% da jornada contratada.</p><p className="mt-2">100%: +5 · 90%: +3 · 80%: +2 · 70%: +1 · 60%: −1 · 50%: −2 · abaixo: −5. Saldo mínimo: zero.</p><p className="mt-2">Asas: 20 metas cumpridas nas últimas 30 avaliações. O histórico importado foi preservado.</p></div></Panel>
 <Panel><h2 className="mb-5 text-lg font-semibold">Sua ficha</h2><form onSubmit={save} className="grid gap-4 sm:grid-cols-2">{(['nome','sobrenome','cargo','data_nascimento'] as const).map(key=><Field key={key} label={{nome:'Nome',sobrenome:'Sobrenome',cargo:'Cargo',data_nascimento:'Nascimento'}[key]}><input className={fieldClass} type={key==='data_nascimento'?'date':'text'} required={key==='nome'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}<div className="sm:col-span-2"><Field label="Responsabilidades"><textarea className={`${fieldClass} h-24 py-2`} value={form.descricao_cargo} onChange={e=>setForm({...form,descricao_cargo:e.target.value})}/></Field></div><p className="text-sm text-muted-foreground sm:col-span-2">{data.areas.find(a=>a.id===me.area_id)?.nome??'Sem área'} · {me.horas_dia_contratadas} h/dia · {me.ativo?'Ativo':'Desativado'}</p><Button disabled={busy||!me.ativo}>Salvar perfil</Button></form></Panel></div>
 <Panel className="mt-5"><h2 className="mb-4 text-lg font-semibold">Histórico de pontuação</h2><div className="max-h-80 overflow-auto">{recent.length===0?<p className="text-muted-foreground">Nenhum dia avaliado ainda.</p>:<table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="py-2">Dia</th><th>Aderência</th><th>Meta</th><th className="text-right">Moedas</th></tr></thead><tbody>{recent.map(p=><tr key={p.id} className="border-b border-border"><td className="py-3">{p.data.split('-').reverse().join('/')}</td><td>{p.percentual}%</td><td>{p.bateu_meta?'Cumprida':'Não atingida'}</td><td className="text-right">{p.moedas_delta>0?'+':''}{p.moedas_delta}</td></tr>)}</tbody></table>}</div></Panel></>;
}
